circleci - cloudfoundry - first attempt

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,5 +23,85 @@ jobs:
 
       - run: mvn clean install spring-boot:repackage -P cloudfoundry
 
+      - run:
+          name: Copy deployment artifacts to workspace
+          command: |
+            cp target/cicd-demo-cf.jar /tmp/cicd-demo-cf.jar
+            cp cloudfoundry/manifest.yml /tmp/
+
       - store_test_results:
           path: target/surefire-reports
+
+      - store_artifacts:
+          path: /tmp/cicd-demo-cf.jar
+
+      - store_artifacts:
+          path: /tmp/manifest.yml
+
+      - persist_to_workspace:
+          root: /tmp
+          paths:
+            - cicd-demo-cf.jar
+            - manifest.yml
+
+  deploy-cf:
+    docker:
+      - image: circleci/openjdk
+    working_directory: ~/deploy
+    steps:
+      # why rebuild something we already tested, rebuilding invalidates any previous confidence?!
+      - attach_workspace:
+          at: /tmp
+
+      - run: queueBuildUntilFrontOfLine 5 #do not run parallel deployments
+      - run:
+          name: Setup CF CLI
+          command: |
+            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
+            sudo dpkg -i cf-cli_amd64.deb
+            cf -v
+            cf api https://api.run.pivotal.io
+            cf auth $CF_USER $CF_PASSWORD
+            cf target -o eddies-org -s development
+
+      - run:
+          name: CF Deploy
+          command: |
+            # Copy deployable jar and CF Manifest to current dir
+            cp /tmp/cicd-demo-cf.jar .
+            cp /tmp/manifest.yml .
+
+            # Push as "dark" instance
+            cf push circleci-dark -f manifest.yml -p cicd-demo-cf.jar -n circleci-dark
+
+            # Verify new version is working on dark URL.
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://circleci-dark.cfapps.io/`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "dark route note available, failing deploy"
+              exit 1
+            fi
+
+            # Send "real" url to new version
+            cf map-route circleci-dark cfapps.io -n cicd-demo
+
+            # Stop sending traffic to previous version
+            cf unmap-route cicd-demo cfapps.io -n cicd-demo
+
+            # stop previous version
+            cf stop cicd-demo
+
+            # delete previous version
+            cf delete cicd-demo -f
+
+            # Switch name of "dark" version to claim correct name
+            cf rename circleci-dark cicd-demo
+
+
+workflows:
+  version: 2
+  build-deploy:
+    jobs:
+      - build
+      - deploy-cf:
+          requires:
+            - build
